export const company = {
  name: "RevUp Consulting Arizona",
  legalName: "RevUp Consulting Arizona",
  tagline: "More Patients. Stronger Practices. Greater Impact.",
  phoneDisplay: "(480) 123-4567",
  phoneTel: "+14801234567",
  email: "info@revupconsultingaz.com",
  websiteDisplay: "www.revupconsultingaz.com",
  websiteUrl: "https://www.revupconsultingaz.com",
  hours: "Monday–Friday, 8:00 a.m.–5:00 p.m. MST",
  serviceArea: "Serving Surgical Practices Nationwide",
  emergency: "Serving surgical practices nationwide",
  street: "Scottsdale, AZ",
  city: "Scottsdale",
  region: "AZ",
  postalCode: "85251",
  country: "US",
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  description:
    "Boutique marketing for surgical excellence. RevUp Consulting Arizona helps surgical practices grow with messaging that respects the operating room.",
};
